sudo: false

language: scala

scala:
  - 2.11.9
  - 2.12.1

jdk:
  - oraclejdk8

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

script:
  - ./sbt -J-Xmx4G -J-XX:MaxPermSize=1G -sbt-version 0.13.13 -scala-version $TRAVIS_SCALA_VERSION 'testOnly -- xonly timefactor 3 exclude travis neverstore'
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6f43e8d682579a80ef5f
    on_success: always
    on_failure: always
    on_start: false
